---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: production
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP